name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy-web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.x

      - name: Publish Web
        run: dotnet publish src/CurrencyApp.Web/CurrencyApp.Web.csproj -c Release -o publish/web

      - name: Deploy Web to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: STIN-web
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_WEB }}
          package: publish/web

  deploy-api:
    runs-on: ubuntu-latest
    needs: deploy-web

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.x

      - name: Publish API
        run: dotnet publish src/CurrencyApp.Api/CurrencyApp.Api.csproj -c Release -o publish/api

      - name: Deploy API to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: STIN-api
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_API }}
          package: publish/api
